export enum NotificationType {
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_STATUS_CHANGED = 'TASK_STATUS_CHANGED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  DEADLINE_SOON = 'DEADLINE_SOON',
  PROJECT_MEMBER_ADDED = 'PROJECT_MEMBER_ADDED',
}
